// app/(auth)/auth/confirm/route.js
// Handles all auth confirmation links generated by the send-auth-email Edge Function.
// URL shape: /auth/confirm?token_hash=...&type=...&next=...

import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function GET(request) {
  const { searchParams, origin } = new URL(request.url);

  const token_hash = searchParams.get("token_hash");
  const type = searchParams.get("type"); // signup | recovery | magiclink | email_change | invite
  const next = searchParams.get("next") ?? "/";

  if (!token_hash || !type) {
    return NextResponse.redirect(
      `${origin}/login?error=Invalid+confirmation+link`
    );
  }

  const supabase = await createClient();

  const { data, error } = await supabase.auth.verifyOtp({
    token_hash,
    type,
  });

  if (error) {
    console.error("Auth confirm error:", error.message);
    return NextResponse.redirect(
      `${origin}/login?error=${encodeURIComponent(error.message)}`
    );
  }

  // For password recovery, always send to the reset-password page
  // so the user can set their new password while their session is active.
  if (type === "recovery") {
    return NextResponse.redirect(`${origin}/reset-password`);
  }

  // For signup / magic link / invite, redirect to role-based dashboard
  // if no explicit `next` was provided.
  if (next === "/" && data.user) {
    const role = data.user.user_metadata?.role ?? "customer";
    const dashboardPath =
      role === "customer"
        ? "/dashboard/customer"
        : `/${role}/dashboard`;
    return NextResponse.redirect(`${origin}${dashboardPath}`);
  }

  return NextResponse.redirect(`${origin}${next}`);
}
