import {
  Wifi,
  ParkingCircle,
  UtensilsCrossed,
  Waves,
  Dumbbell,
  Bed,
  Bath,
  Users,
  ChefHat,
  ShieldCheck,
  CarFront,
  MapPin,
  Truck,
  Projector,
  Star,
  Hotel,
  BedDouble,
  Building2,
  Home,
  AirVent,
  BatteryCharging,
  Bell,
  WashingMachine,
  RefreshCw,
  XCircle,
  Percent,
  Globe,
  Pizza,
  Fish,
  Leaf,
  Sprout,
  WheatOff,
  HeartPulse,
  Heart,
  Package,
  FastForward,
  Speaker,
  Theater,
  Lightbulb,
  Music,
  Briefcase,
  Cake,
  Rocket,
  Ticket,
  Camera,
  Mic,
  Palette,
  Music2,
  UserCheck,
  Clock,
  Calendar,
  Bike,
  Car,
  Box,
  Map,
  Radio,
  Video,
  AlertTriangle,
  Drone,
  Footprints,
  Search,
  ClipboardCheck,
  Siren,
  Settings,
  Fuel,
  Bus,
  Plane,
  Brush,
  ShoppingCart,
  Wrench,
  ArrowUpDown,
  Sofa,
  Microwave,
  Refrigerator,
  CreditCard,
  IdCard,
  Utensils,
  User,
  Shield,
  Store,
  Flame,
  CheckCircle,
  Warehouse,
  Mail,
  CookingPot,
  Moon,
} from "lucide-react";

export const getFeatureIcon = (featureKey, value) => {
  const keyLower = (featureKey || "").toLowerCase();
  const valueLower = (value || "").toLowerCase();

  // Icon mappings for specific field-value pairs
  const valueIconMap = {
    // Hotels
    "room_type.standard": <Hotel className="h-4 w-4 mr-2" />,
    "room_type.deluxe": <Star className="h-4 w-4 mr-2" />,
    "room_type.suite": <BedDouble className="h-4 w-4 mr-2" />,
    "room_type.penthouse": <Building2 className="h-4 w-4 mr-2" />,
    "room_type.apartment": <Home className="h-4 w-4 mr-2" />,
    "amenities.wifi": <Wifi className="h-4 w-4 mr-2" />,
    "amenities.ac": <AirVent className="h-4 w-4 mr-2" />,
    "amenities.power_backup": <BatteryCharging className="h-4 w-4 mr-2" />,
    "amenities.swimming_pool": <Waves className="h-4 w-4 mr-2" />,
    "amenities.gym": <Dumbbell className="h-4 w-4 mr-2" />,
    "amenities.restaurant": <UtensilsCrossed className="h-4 w-4 mr-2" />,
    "amenities.parking": <ParkingCircle className="h-4 w-4 mr-2" />,
    "amenities.room_service": <Bell className="h-4 w-4 mr-2" />,
    "amenities.laundry": <WashingMachine className="h-4 w-4 mr-2" />,
    "amenities.security": <ShieldCheck className="h-4 w-4 mr-2" />,
    "cancellation_policy.free_24h": <RefreshCw className="h-4 w-4 mr-2" />,
    "cancellation_policy.free_48h": <RefreshCw className="h-4 w-4 mr-2" />,
    "cancellation_policy.free_7d": <RefreshCw className="h-4 w-4 mr-2" />,
    "cancellation_policy.non_refundable": <XCircle className="h-4 w-4 mr-2" />,
    "cancellation_policy.partial_refunded": (
      <Percent className="h-4 w-4 mr-2" />
    ),

    // Food
    "cuisine_type.nigerian": <Utensils className="h-4 w-4 mr-2" />,
    "cuisine_type.continental": <Globe className="h-4 w-4 mr-2" />,
    "cuisine_type.chinese": <Utensils className="h-4 w-4 mr-2" />,
    "cuisine_type.italian": <Pizza className="h-4 w-4 mr-2" />,
    "cuisine_type.indian": <Utensils className="h-4 w-4 mr-2" />,
    "cuisine_type.fast_food": <FastForward className="h-4 w-4 mr-2" />,
    "cuisine_type.seafood": <Fish className="h-4 w-4 mr-2" />,
    "cuisine_type.vegetarian": <Leaf className="h-4 w-4 mr-2" />,
    "cuisine_type.intercontinental": <Globe className="h-4 w-4 mr-2" />,
    "service_type.dine_in": <UtensilsCrossed className="h-4 w-4 mr-2" />,
    "service_type.takeaway": <Package className="h-4 w-4 mr-2" />,
    "service_type.delivery": <Truck className="h-4 w-4 mr-2" />,
    "service_type.catering": <ChefHat className="h-4 w-4 mr-2" />,
    "service_type.buffet": <Utensils className="h-4 w-4 mr-2" />,
    "special_diets.halal": <Moon className="h-4 w-4 mr-2" />,
    "special_diets.vegetarian": <Leaf className="h-4 w-4 mr-2" />,
    "special_diets.vegan": <Sprout className="h-4 w-4 mr-2" />,
    "special_diets.gluten_free": <WheatOff className="h-4 w-4 mr-2" />,
    "special_diets.diabetic_friendly": <HeartPulse className="h-4 w-4 mr-2" />,
    "special_diets.low_sodium": <Heart className="h-4 w-4 mr-2" />,
    delivery_areas: <MapPin className="h-4 w-4 mr-2" />,

    // Events (Event Center)
    "amenities.projector": <Projector className="h-4 w-4 mr-2" />,
    "amenities.sound_system": <Speaker className="h-4 w-4 mr-2" />,
    "amenities.catering": <ChefHat className="h-4 w-4 mr-2" />,
    "amenities.parking": <ParkingCircle className="h-4 w-4 mr-2" />,
    "amenities.stage": <Theater className="h-4 w-4 mr-2" />,
    "amenities.lighting": <Lightbulb className="h-4 w-4 mr-2" />,
    "amenities.generator": <BatteryCharging className="h-4 w-4 mr-2" />,
    "amenities.ac": <AirVent className="h-4 w-4 mr-2" />,
    "amenities.security": <ShieldCheck className="h-4 w-4 mr-2" />,
    "amenities.wifi": <Wifi className="h-4 w-4 mr-2" />,
    "cancellation_policy.free_48h": <RefreshCw className="h-4 w-4 mr-2" />,
    "cancellation_policy.free_7d": <RefreshCw className="h-4 w-4 mr-2" />,
    "cancellation_policy.partial_50": <Percent className="h-4 w-4 mr-2" />,
    "cancellation_policy.non_refundable": <XCircle className="h-4 w-4 mr-2" />,

    // Events (Event Organizer)
    "event_types.wedding": <Heart className="h-4 w-4 mr-2" />,
    "event_types.concert": <Music className="h-4 w-4 mr-2" />,
    "event_types.conference": <Briefcase className="h-4 w-4 mr-2" />,
    "event_types.birthday": <Cake className="h-4 w-4 mr-2" />,
    "event_types.corporate": <Building2 className="h-4 w-4 mr-2" />,
    "event_types.social": <Users className="h-4 w-4 mr-2" />,
    "event_types.product_launch": <Rocket className="h-4 w-4 mr-2" />,
    "services_included.ticketing": <Ticket className="h-4 w-4 mr-2" />,
    "services_included.security": <ShieldCheck className="h-4 w-4 mr-2" />,
    "services_included.catering": <ChefHat className="h-4 w-4 mr-2" />,
    "services_included.photography": <Camera className="h-4 w-4 mr-2" />,
    "services_included.mc": <Mic className="h-4 w-4 mr-2" />,
    "services_included.decoration": <Palette className="h-4 w-4 mr-2" />,
    "services_included.music": <Music2 className="h-4 w-4 mr-2" />,
    "services_included.ushers": <UserCheck className="h-4 w-4 mr-2" />,

    // Logistics
    "service_types.same_day": <Clock className="h-4 w-4 mr-2" />,
    "service_types.next_day": <Calendar className="h-4 w-4 mr-2" />,
    "service_types.express": <FastForward className="h-4 w-4 mr-2" />,
    "service_types.standard": <Truck className="h-4 w-4 mr-2" />,
    "service_types.moving": <Home className="h-4 w-4 mr-2" />,
    "service_types.freight": <Package className="h-4 w-4 mr-2" />,
    "service_types.courier": <Mail className="h-4 w-4 mr-2" />,
    "service_types.warehousing": <Warehouse className="h-4 w-4 mr-2" />,
    "vehicle_types.motorcycle": <Bike className="h-4 w-4 mr-2" />,
    "vehicle_types.car": <Car className="h-4 w-4 mr-2" />,
    "vehicle_types.van": <Truck className="h-4 w-4 mr-2" />,
    "vehicle_types.pickup": <CarFront className="h-4 w-4 mr-2" />,
    "vehicle_types.truck": <Truck className="h-4 w-4 mr-2" />,
    "vehicle_types.container": <Box className="h-4 w-4 mr-2" />,
    "delivery_time.1_2_hours": <Clock className="h-4 w-4 mr-2" />,
    "delivery_time.same_day": <Clock className="h-4 w-4 mr-2" />,
    "delivery_time.next_day": <Calendar className="h-4 w-4 mr-2" />,
    "delivery_time.2_3_days": <Calendar className="h-4 w-4 mr-2" />,
    "delivery_time.within_week": <Calendar className="h-4 w-4 mr-2" />,
    "tracking_available.yes": <Map className="h-4 w-4 mr-2" />,
    "tracking_available.partial": <MapPin className="h-4 w-4 mr-2" />,
    "tracking_available.no": <XCircle className="h-4 w-4 mr-2" />,
    "insurance_covered.comprehensive": <Shield className="h-4 w-4 mr-2" />,
    "insurance_covered.third_party": <Shield className="h-4 w-4 mr-2" />,
    "insurance_covered.optional": <Shield className="h-4 w-4 mr-2" />,
    "insurance_covered.none": <XCircle className="h-4 w-4 mr-2" />,
    service_areas: <MapPin className="h-4 w-4 mr-2" />,

    // Security
    "security_types.event": <ShieldCheck className="h-4 w-4 mr-2" />,
    "security_types.personal": <UserCheck className="h-4 w-4 mr-2" />,
    "security_types.corporate": <Briefcase className="h-4 w-4 mr-2" />,
    "security_types.residential": <Home className="h-4 w-4 mr-2" />,
    "security_types.retail": <Store className="h-4 w-4 mr-2" />,
    "security_types.patrol": <Footprints className="h-4 w-4 mr-2" />,
    "security_types.investigation": <Search className="h-4 w-4 mr-2" />,
    "security_types.consultancy": <ClipboardCheck className="h-4 w-4 mr-2" />,
    duration: <Clock className="h-4 w-4 mr-2" />,
    "certifications.nscdc": <ShieldCheck className="h-4 w-4 mr-2" />,
    "certifications.psira": <ShieldCheck className="h-4 w-4 mr-2" />,
    "certifications.sia": <ShieldCheck className="h-4 w-4 mr-2" />,
    "certifications.first_aid": <HeartPulse className="h-4 w-4 mr-2" />,
    "certifications.fire_safety": <Flame className="h-4 w-4 mr-2" />,
    "equipment.cctv": <Video className="h-4 w-4 mr-2" />,
    "equipment.metal_detector": <AlertTriangle className="h-4 w-4 mr-2" />,
    "equipment.walkie_talkie": <Radio className="h-4 w-4 mr-2" />,
    "equipment.body_cameras": <Camera className="h-4 w-4 mr-2" />,
    "equipment.security_drones": <Drone className="h-4 w-4 mr-2" />,
    "background_check.yes": <CheckCircle className="h-4 w-4 mr-2" />,
    "background_check.partial": <CheckCircle className="h-4 w-4 mr-2" />,
    "background_check.no": <XCircle className="h-4 w-4 mr-2" />,
    response_time: <Siren className="h-4 w-4 mr-2" />,

    // Car Rentals
    "vehicle_categories.economy": <Car className="h-4 w-4 mr-2" />,
    "vehicle_categories.compact": <Car className="h-4 w-4 mr-2" />,
    "vehicle_categories.standard": <CarFront className="h-4 w-4 mr-2" />,
    "vehicle_categories.luxury": <Star className="h-4 w-4 mr-2" />,
    "vehicle_categories.suv": <Car className="h-4 w-4 mr-2" />,
    "vehicle_categories.minivan": <Bus className="h-4 w-4 mr-2" />,
    "vehicle_categories.pickup": <Truck className="h-4 w-4 mr-2" />,
    "vehicle_categories.convertible": <Car className="h-4 w-4 mr-2" />,
    "vehicle_categories.electric": <BatteryCharging className="h-4 w-4 mr-2" />,
    transmission_types: <Settings className="h-4 w-4 mr-2" />,
    "fuel_types.petrol": <Fuel className="h-4 w-4 mr-2" />,
    "fuel_types.diesel": <Fuel className="h-4 w-4 mr-2" />,
    "fuel_types.hybrid": <Leaf className="h-4 w-4 mr-2" />,
    "fuel_types.electric": <BatteryCharging className="h-4 w-4 mr-2" />,
    rental_duration: <Clock className="h-4 w-4 mr-2" />,
    "driver_service.self_drive": <Car className="h-4 w-4 mr-2" />,
    "driver_service.with_driver": <User className="h-4 w-4 mr-2" />,
    "driver_service.both": <Users className="h-4 w-4 mr-2" />,
    "delivery_pickup.yes": <Truck className="h-4 w-4 mr-2" />,
    "delivery_pickup.paid": <CreditCard className="h-4 w-4 mr-2" />,
    "delivery_pickup.no": <XCircle className="h-4 w-4 mr-2" />,
    license_requirement: <IdCard className="h-4 w-4 mr-2" />,
    "insurance_coverage.comprehensive": <Shield className="h-4 w-4 mr-2" />,
    "insurance_coverage.third_party": <Shield className="h-4 w-4 mr-2" />,
    "insurance_coverage.cdw": <Shield className="h-4 w-4 mr-2" />,
    "insurance_coverage.none": <XCircle className="h-4 w-4 mr-2" />,

    // Serviced Apartments
    apartment_types: <Home className="h-4 w-4 mr-2" />,
    "apartment_types.penthouse": <Building2 className="h-4 w-4 mr-2" />,
    minimum_stay: <Calendar className="h-4 w-4 mr-2" />,
    "services_included.housekeeping": <Brush className="h-4 w-4 mr-2" />,
    "services_included.laundry": <WashingMachine className="h-4 w-4 mr-2" />,
    "services_included.concierge": <Bell className="h-4 w-4 mr-2" />,
    "services_included.room_service": <Utensils className="h-4 w-4 mr-2" />,
    "services_included.grocery_shopping": (
      <ShoppingCart className="h-4 w-4 mr-2" />
    ),
    "services_included.airport_transfer": <Plane className="h-4 w-4 mr-2" />,
    "services_included.maintenance": <Wrench className="h-4 w-4 mr-2" />,
    "amenities.wifi": <Wifi className="h-4 w-4 mr-2" />,
    "amenities.ac": <AirVent className="h-4 w-4 mr-2" />,
    "amenities.power_backup": <BatteryCharging className="h-4 w-4 mr-2" />,
    "amenities.kitchen": <Utensils className="h-4 w-4 mr-2" />,
    "amenities.parking": <ParkingCircle className="h-4 w-4 mr-2" />,
    "amenities.security": <ShieldCheck className="h-4 w-4 mr-2" />,
    "amenities.gym": <Dumbbell className="h-4 w-4 mr-2" />,
    "amenities.pool": <Waves className="h-4 w-4 mr-2" />,
    "amenities.elevator": <ArrowUpDown className="h-4 w-4 mr-2" />,
    target_guests: <Users className="h-4 w-4 mr-2" />,
    furnishing: <Sofa className="h-4 w-4 mr-2" />,
    "kitchen_facilities.microwave": <Microwave className="h-4 w-4 mr-2" />,
    "kitchen_facilities.refrigerator": (
      <Refrigerator className="h-4 w-4 mr-2" />
    ),
    "kitchen_facilities.gas_cooker": <Utensils className="h-4 w-4 mr-2" />,
    "kitchen_facilities.electric_cooker": <Utensils className="h-4 w-4 mr-2" />,
    "kitchen_facilities.cookware": <CookingPot className="h-4 w-4 mr-2" />,
    "kitchen_facilities.dishwasher": (
      <WashingMachine className="h-4 w-4 mr-2" />
    ),
    payment_terms: <CreditCard className="h-4 w-4 mr-2" />,
  };

  // Generic field-based icons
  const fieldIconMap = {
    wifi: <Wifi className="h-4 w-4 mr-2" />,
    parking: <ParkingCircle className="h-4 w-4 mr-2" />,
    restaurant: <UtensilsCrossed className="h-4 w-4 mr-2" />,
    swimming_pool: <Waves className="h-4 w-4 mr-2" />,
    pool: <Waves className="h-4 w-4 mr-2" />,
    gym: <Dumbbell className="h-4 w-4 mr-2" />,
    bedrooms: <Bed className="h-4 w-4 mr-2" />,
    bathrooms: <Bath className="h-4 w-4 mr-2" />,
    capacity: <Users className="h-4 w-4 mr-2" />,
    cuisine_type: <ChefHat className="h-4 w-4 mr-2" />,
    service_type: <Utensils className="h-4 w-4 mr-2" />,
    vehicle_type: <CarFront className="h-4 w-4 mr-2" />,
    vehicle_types: <CarFront className="h-4 w-4 mr-2" />,
    service_areas: <MapPin className="h-4 w-4 mr-2" />,
    security_types: <ShieldCheck className="h-4 w-4 mr-2" />,
    delivery_areas: <Truck className="h-4 w-4 mr-2" />,
    projector: <Projector className="h-4 w-4 mr-2" />,
  };

  // Check for specific value-based icon
  const specificKey = valueLower ? `${keyLower}.${valueLower}` : keyLower;
  return (
    valueIconMap[specificKey] ||
    fieldIconMap[keyLower] || <Star className="h-4 w-4 mr-2" />
  );
};
