"use client";

const VARIANTS = [
  {
    key: "short",
    label: "Short title & venue",
    desc: "Jazz Night · Lagos Arena · VIP",
  },
  {
    key: "medium",
    label: "Medium title & venue",
    desc: "Afrobeats Summer Festival · Eko Convention Centre · General Admission + seat",
  },
  {
    key: "long",
    label: "Long title, venue & ticket type",
    desc: "Grand Annual Pan-African … · Tafawa Balewa Square, Lagos Island … · Premium Early-Bird Weekend Pass",
  },
  {
    key: "verylong",
    label: "Very long — all fields overflowing",
    desc: "Full paragraph title, multi-line address venue, verbose ticket type, compound seat number",
  },
  {
    key: "missing",
    label: "All fields missing / empty",
    desc: "Falls back to N/A / TBD — tests graceful degradation",
  },
];

export default function TicketPreviewPage() {
  return (
    <div className="min-h-screen bg-gray-100 py-10 px-6">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-2xl font-semibold text-gray-900 mb-1">
          Ticket PDF Preview
        </h1>
        <p className="text-sm text-gray-500 mb-8">
          Each panel loads the live PDF generated by{" "}
          <code className="bg-gray-200 px-1 rounded text-xs">
            lib/ticketGenerator.js
          </code>
          . Resize the browser to check how the embed scales. Reload a frame to
          refresh.
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-8">
          {VARIANTS.map(({ key, label, desc }) => (
            <div key={key} className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <div className="px-4 py-3 border-b border-gray-100">
                <p className="text-sm font-medium text-gray-900">{label}</p>
                <p className="text-xs text-gray-400 mt-0.5 leading-snug">{desc}</p>
              </div>
              <div className="bg-gray-50 flex items-center justify-center p-4">
                <iframe
                  src={`/api/ticket-preview?variant=${key}`}
                  title={label}
                  className="w-full rounded border border-gray-200 shadow-inner"
                  style={{ height: 520 }}
                />
              </div>
              <div className="px-4 py-2 border-t border-gray-100 flex items-center justify-between">
                <span className="text-xs text-gray-400 font-mono">
                  ?variant={key}
                </span>
                <a
                  href={`/api/ticket-preview?variant=${key}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-purple-600 hover:text-purple-700 font-medium"
                >
                  Open PDF ↗
                </a>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
